config/routes.rb
EmployeeProject::Application.routes.draw do
  root to: "teams#index"

  resources :employees
  resources :employee_profiles

  resources :teams
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :supervisor_id, :subordinate_ids,
                  :supervised_team_ids, :team_ids

  has_many :subordinates, :class_name => "Employee",
           :foreign_key => :supervisor_id

  belongs_to :supervisor, :class_name => "Employee"

  has_many :supervised_teams, :class_name => "Team",
           :inverse_of => :supervisor,
           :foreign_key => :supervisor_id

  has_one :employee_profile

  has_many :team_memberships
  has_many :teams, :through => :team_memberships

  validates :name, :presence => true
end

app/models/employee_profile.rb
class EmployeeProfile < ActiveRecord::Base
  attr_accessible :height, :fav_food, :fav_day, :birthday,
                  :salary, :photo_url, :employee_id

  belongs_to :employee

  def age
    total_seconds = Time.now - birthday
    seconds_in_year = 365.25 * 24 * 60 * 60
    (total_seconds / seconds_in_year).to_i
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :supervisor_id, :member_ids

  has_many :team_memberships
  has_many :members, :through => :team_memberships,
           :source => :employee
  belongs_to  :supervisor, :class_name => "Employee",
              :inverse_of => :supervised_teams
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  attr_accessible :employee_id, :team_id
  belongs_to :employee
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employee_profiles_controller.rb
class EmployeeProfilesController < ApplicationController
  def new
    if params[:employee_id]
      @employee = Employee.find(params[:employee_id])
      @employee_profile = EmployeeProfile.new(:employee_id => params[:employee_id])
    end
  end

  def create
    @employee_profile = EmployeeProfile.new(params[:employee_profile])
    if @employee_profile.save
      redirect_to employee_profile_url(@employee_profile)
    else
      render :new
    end
  end

  def edit
    @employee_profile = EmployeeProfile.find(params[:id])
    @employee = @employee_profile.employee
  end

  def update
    @employee_profile = EmployeeProfile.find(params[:id])

    if @employee_profile.update_attributes(params[:employee_profile])
      redirect_to employee_profile_url(@employee_profile)
    else
      render :edit
    end
  end

  def show
    @employee_profile = EmployeeProfile.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    @employee = Employee.new
    @teams = Team.all
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to @employee
    else
      render :new
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
    @teams = Team.all
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      redirect_to @employee
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employee_profiles/show.html.erb
<h1>Profile for <%= @employee.name %> </h1>

Date of Birth: <%= @employee_profile.birthday %><br>
Age:  <%= @employee_profile.age %><br>
Height (in inches): <%= @employee_profile.height %><br>
Favorite Food: <%= @employee_profile.fav_food %><br>
Favorite Day: <%= @employee_profile.fav_day %><br>
Link to Photo: <%= @employee_profile.photo_url %>
<br>
Salary: $<%= @employee_profile.salary %><br>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :supervisor %>
  <%= f.collection_select :supervisor_id, Employee.all, :id, :name%>
  <br>
  <% @teams.each do |team| %>
    <label><input type="checkbox" name="student[team_ids][]"
     value="<%= team.id %>" <%= "checked" if
     @employee.teams.include?(team) %>>
    <%= team.name %></label><br>
  <% end %>

  <input type="hidden" name="student[team_ids][]" value="">

  <%= f.submit %>

<% end %>

app/views/employees/edit.html.erb
<%= render partial: 'form' %>

app/views/employees/new.html.erb
<%= render partial: 'form' %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<%= link_to "Profile",
 employee_profile_url(@employee.employee_profile)%>

  Supervisor:
  <% if @employee.supervisor %>
    <%= link_to @employee.supervisor.name, employee_url(@employee.supervisor) %>
  <% else %>
    None
  <% end %>

  <br>

  Subordinates:

  <% if @employee.subordinates.empty? %>
    None
  <% else %>
    <% @employee.subordinates.each do |sub|%>
      <%= link_to sub.name, employee_url(sub) %><br>
    <% end %>
  <% end %>

  <br>

  Teams:

  <% if @employee.teams.empty? %>
    None
  <% else %>
    <% @employee.teams.each do |team|%>
      <%= link_to team.name, team_url(team) %><br>
    <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>